# -*- coding: utf-8 -*-
# AUTO-GENERATED by _gen_sku_meta.py — do not edit by hand.
# 11-language TDK for the 27 SKU spec pages.
SKU_META = {
 "products/cgm-12w": {
  "en": {
   "title": "CGM-12W 12V LED Adapter Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGM-12W 12W LED adapter, 12V output. 100-240V input, CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGM-12W 12V LED 适配器 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGM-12W 12W LED 适配器, 12V 输出. 100-240V 输入, CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGM-12W 12V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-12W 12W adaptadores LED, 12V salida. entrada 100-240V, CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGM-12W 12V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-12W 12W adaptadores LED, 12V saída. entrada 100-240V, CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGM-12W 12V LED-адаптер Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGM-12W 12W LED-адаптер, 12V выход. вход 100-240V, CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGM-12W 12V adaptateurs LED Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGM-12W 12W adaptateurs LED, 12V sortie. entrée 100-240V, CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGM-12W 12V LED-Adapter Hersteller | CHUGAO OEM ODM",
   "desc": "China CGM-12W 12W LED-Adapter, 12V Ausgang. 100-240V Eingang, CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGM-12W 12V محولات LED مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGM-12W 12W محولات LED, 12V إخراج. إدخال 100-240V, CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGM-12W 12V LED アダプター 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGM-12W 12W LED アダプター, 12V 出力. 100-240V 入力, CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGM-12W 12V LED 어댑터 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGM-12W 12W LED 어댑터, 12V 출력. 100-240V 입력, CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGM-12W 12V adattatori LED Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGM-12W 12W adattatori LED, 12V uscita. ingresso 100-240V, CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgm-24w": {
  "en": {
   "title": "CGM-24W 12V/24V LED Adapter Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGM-24W 24W LED adapter, 12V/24V output. 100-240V input, CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGM-24W 12V/24V LED 适配器 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGM-24W 24W LED 适配器, 12V/24V 输出. 100-240V 输入, CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGM-24W 12V/24V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-24W 24W adaptadores LED, 12V/24V salida. entrada 100-240V, CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGM-24W 12V/24V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-24W 24W adaptadores LED, 12V/24V saída. entrada 100-240V, CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGM-24W 12V/24V LED-адаптер Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGM-24W 24W LED-адаптер, 12V/24V выход. вход 100-240V, CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGM-24W 12V/24V adaptateurs LED Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGM-24W 24W adaptateurs LED, 12V/24V sortie. entrée 100-240V, CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGM-24W 12V/24V LED-Adapter Hersteller | CHUGAO OEM ODM",
   "desc": "China CGM-24W 24W LED-Adapter, 12V/24V Ausgang. 100-240V Eingang, CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGM-24W 12V/24V محولات LED مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGM-24W 24W محولات LED, 12V/24V إخراج. إدخال 100-240V, CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGM-24W 12V/24V LED アダプター 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGM-24W 24W LED アダプター, 12V/24V 出力. 100-240V 入力, CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGM-24W 12V/24V LED 어댑터 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGM-24W 24W LED 어댑터, 12V/24V 출력. 100-240V 입력, CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGM-24W 12V/24V adattatori LED Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGM-24W 24W adattatori LED, 12V/24V uscita. ingresso 100-240V, CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgm-36w": {
  "en": {
   "title": "CGM-36W 12V/24V/36V LED Adapter Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGM-36W 36W LED adapter, 12V/24V/36V output. 100-240V input, CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGM-36W 12V/24V/36V LED 适配器 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGM-36W 36W LED 适配器, 12V/24V/36V 输出. 100-240V 输入, CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGM-36W 12V/24V/36V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-36W 36W adaptadores LED, 12V/24V/36V salida. entrada 100-240V, CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGM-36W 12V/24V/36V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-36W 36W adaptadores LED, 12V/24V/36V saída. entrada 100-240V, CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGM-36W 12V/24V/36V LED-адаптер Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGM-36W 36W LED-адаптер, 12V/24V/36V выход. вход 100-240V, CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGM-36W 12V/24V/36V adaptateurs LED Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGM-36W 36W adaptateurs LED, 12V/24V/36V sortie. entrée 100-240V, CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGM-36W 12V/24V/36V LED-Adapter Hersteller | CHUGAO OEM ODM",
   "desc": "China CGM-36W 36W LED-Adapter, 12V/24V/36V Ausgang. 100-240V Eingang, CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGM-36W 12V/24V/36V محولات LED مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGM-36W 36W محولات LED, 12V/24V/36V إخراج. إدخال 100-240V, CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGM-36W 12V/24V/36V LED アダプター 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGM-36W 36W LED アダプター, 12V/24V/36V 出力. 100-240V 入力, CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGM-36W 12V/24V/36V LED 어댑터 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGM-36W 36W LED 어댑터, 12V/24V/36V 출력. 100-240V 입력, CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGM-36W 12V/24V/36V adattatori LED Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGM-36W 36W adattatori LED, 12V/24V/36V uscita. ingresso 100-240V, CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgm-60w": {
  "en": {
   "title": "CGM-60W 12V/24V LED Adapter Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGM-60W 60W LED adapter, 12V/24V output. 100-240V input, CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGM-60W 12V/24V LED 适配器 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGM-60W 60W LED 适配器, 12V/24V 输出. 100-240V 输入, CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGM-60W 12V/24V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-60W 60W adaptadores LED, 12V/24V salida. entrada 100-240V, CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGM-60W 12V/24V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-60W 60W adaptadores LED, 12V/24V saída. entrada 100-240V, CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGM-60W 12V/24V LED-адаптер Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGM-60W 60W LED-адаптер, 12V/24V выход. вход 100-240V, CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGM-60W 12V/24V adaptateurs LED Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGM-60W 60W adaptateurs LED, 12V/24V sortie. entrée 100-240V, CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGM-60W 12V/24V LED-Adapter Hersteller | CHUGAO OEM ODM",
   "desc": "China CGM-60W 60W LED-Adapter, 12V/24V Ausgang. 100-240V Eingang, CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGM-60W 12V/24V محولات LED مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGM-60W 60W محولات LED, 12V/24V إخراج. إدخال 100-240V, CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGM-60W 12V/24V LED アダプター 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGM-60W 60W LED アダプター, 12V/24V 出力. 100-240V 入力, CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGM-60W 12V/24V LED 어댑터 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGM-60W 60W LED 어댑터, 12V/24V 출력. 100-240V 입력, CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGM-60W 12V/24V adattatori LED Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGM-60W 60W adattatori LED, 12V/24V uscita. ingresso 100-240V, CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgm-6w": {
  "en": {
   "title": "CGM-6W 12V LED Adapter Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGM-6W 6W LED adapter, 12V output. 100-240V input, CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGM-6W 12V LED 适配器 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGM-6W 6W LED 适配器, 12V 输出. 100-240V 输入, CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGM-6W 12V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-6W 6W adaptadores LED, 12V salida. entrada 100-240V, CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGM-6W 12V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-6W 6W adaptadores LED, 12V saída. entrada 100-240V, CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGM-6W 12V LED-адаптер Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGM-6W 6W LED-адаптер, 12V выход. вход 100-240V, CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGM-6W 12V adaptateurs LED Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGM-6W 6W adaptateurs LED, 12V sortie. entrée 100-240V, CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGM-6W 12V LED-Adapter Hersteller | CHUGAO OEM ODM",
   "desc": "China CGM-6W 6W LED-Adapter, 12V Ausgang. 100-240V Eingang, CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGM-6W 12V محولات LED مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGM-6W 6W محولات LED, 12V إخراج. إدخال 100-240V, CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGM-6W 12V LED アダプター 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGM-6W 6W LED アダプター, 12V 出力. 100-240V 入力, CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGM-6W 12V LED 어댑터 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGM-6W 6W LED 어댑터, 12V 출력. 100-240V 입력, CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGM-6W 12V adattatori LED Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGM-6W 6W adattatori LED, 12V uscita. ingresso 100-240V, CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgm-48w": {
  "en": {
   "title": "CGM-48W 12V/24V LED Adapter Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGM-48W 48W LED adapter, 12V/24V output. 100-240V input, CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGM-48W 12V/24V LED 适配器 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGM-48W 48W LED 适配器, 12V/24V 输出. 100-240V 输入, CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGM-48W 12V/24V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-48W 48W adaptadores LED, 12V/24V salida. entrada 100-240V, CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGM-48W 12V/24V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-48W 48W adaptadores LED, 12V/24V saída. entrada 100-240V, CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGM-48W 12V/24V LED-адаптер Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGM-48W 48W LED-адаптер, 12V/24V выход. вход 100-240V, CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGM-48W 12V/24V adaptateurs LED Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGM-48W 48W adaptateurs LED, 12V/24V sortie. entrée 100-240V, CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGM-48W 12V/24V LED-Adapter Hersteller | CHUGAO OEM ODM",
   "desc": "China CGM-48W 48W LED-Adapter, 12V/24V Ausgang. 100-240V Eingang, CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGM-48W 12V/24V محولات LED مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGM-48W 48W محولات LED, 12V/24V إخراج. إدخال 100-240V, CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGM-48W 12V/24V LED アダプター 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGM-48W 48W LED アダプター, 12V/24V 出力. 100-240V 入力, CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGM-48W 12V/24V LED 어댑터 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGM-48W 48W LED 어댑터, 12V/24V 출력. 100-240V 입력, CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGM-48W 12V/24V adattatori LED Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGM-48W 48W adattatori LED, 12V/24V uscita. ingresso 100-240V, CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgm-72w": {
  "en": {
   "title": "CGM-72W 12V/24V LED Adapter Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGM-72W 72W LED adapter, 12V/24V output. 100-240V input, CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGM-72W 12V/24V LED 适配器 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGM-72W 72W LED 适配器, 12V/24V 输出. 100-240V 输入, CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGM-72W 12V/24V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-72W 72W adaptadores LED, 12V/24V salida. entrada 100-240V, CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGM-72W 12V/24V adaptadores LED Fabricante | CHUGAO OEM ODM",
   "desc": "China CGM-72W 72W adaptadores LED, 12V/24V saída. entrada 100-240V, CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGM-72W 12V/24V LED-адаптер Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGM-72W 72W LED-адаптер, 12V/24V выход. вход 100-240V, CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGM-72W 12V/24V adaptateurs LED Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGM-72W 72W adaptateurs LED, 12V/24V sortie. entrée 100-240V, CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGM-72W 12V/24V LED-Adapter Hersteller | CHUGAO OEM ODM",
   "desc": "China CGM-72W 72W LED-Adapter, 12V/24V Ausgang. 100-240V Eingang, CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGM-72W 12V/24V محولات LED مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGM-72W 72W محولات LED, 12V/24V إخراج. إدخال 100-240V, CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGM-72W 12V/24V LED アダプター 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGM-72W 72W LED アダプター, 12V/24V 出力. 100-240V 入力, CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGM-72W 12V/24V LED 어댑터 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGM-72W 72W LED 어댑터, 12V/24V 출력. 100-240V 입력, CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGM-72W 12V/24V adattatori LED Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGM-72W 72W adattatori LED, 12V/24V uscita. ingresso 100-240V, CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/c-100w": {
  "en": {
   "title": "C-100W Indoor LED Driver 12V/24V Manufacturer | CHUGAO OEM ODM",
   "desc": "China C-100W 100W indoor LED driver, 12V/24V, active PFC. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "C-100W 室内 LED 驱动电源 12V/24V 厂家 | CHUGAO OEM ODM",
   "desc": "中国 C-100W 100W 室内 LED 驱动电源, 12V/24V, 主动 PFC. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "C-100W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China C-100W 100W driver LED de interior, 12V/24V, PFC activo. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "C-100W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China C-100W 100W driver LED de interior, 12V/24V, PFC ativo. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "C-100W драйвер LED для помещений 12V/24V Производитель | CHUGAO OEM ODM",
   "desc": "Китай C-100W 100W драйвер LED для помещений, 12V/24V, активный PFC. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "C-100W driver LED d’intérieur 12V/24V Fabricant | CHUGAO OEM ODM",
   "desc": "Chine C-100W 100W driver LED d’intérieur, 12V/24V, PFC actif. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "C-100W LED-Treiber Innen 12V/24V Hersteller | CHUGAO OEM ODM",
   "desc": "China C-100W 100W LED-Treiber Innen, 12V/24V, aktiver PFC. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "C-100W مشغل LED داخلي 12V/24V مصنع | CHUGAO OEM ODM",
   "desc": "الصين C-100W 100W مشغل LED داخلي, 12V/24V, PFC نشط. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "C-100W 屋内用 LED ドライバー 12V/24V 製造元 | CHUGAO OEM ODM",
   "desc": "中国 C-100W 100W 屋内用 LED ドライバー, 12V/24V, アクティブ PFC. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "C-100W 실내용 LED 구동장치 12V/24V 제조사 | CHUGAO OEM ODM",
   "desc": "중국 C-100W 100W 실내용 LED 구동장치, 12V/24V, 액티브 PFC. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "C-100W driver LED da interno 12V/24V Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina C-100W 100W driver LED da interno, 12V/24V, PFC attivo. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/c-200w": {
  "en": {
   "title": "C-200W Indoor LED Driver 12V/24V Manufacturer | CHUGAO OEM ODM",
   "desc": "China C-200W 200W indoor LED driver, 12V/24V, active PFC. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "C-200W 室内 LED 驱动电源 12V/24V 厂家 | CHUGAO OEM ODM",
   "desc": "中国 C-200W 200W 室内 LED 驱动电源, 12V/24V, 主动 PFC. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "C-200W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China C-200W 200W driver LED de interior, 12V/24V, PFC activo. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "C-200W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China C-200W 200W driver LED de interior, 12V/24V, PFC ativo. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "C-200W драйвер LED для помещений 12V/24V Производитель | CHUGAO OEM ODM",
   "desc": "Китай C-200W 200W драйвер LED для помещений, 12V/24V, активный PFC. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "C-200W driver LED d’intérieur 12V/24V Fabricant | CHUGAO OEM ODM",
   "desc": "Chine C-200W 200W driver LED d’intérieur, 12V/24V, PFC actif. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "C-200W LED-Treiber Innen 12V/24V Hersteller | CHUGAO OEM ODM",
   "desc": "China C-200W 200W LED-Treiber Innen, 12V/24V, aktiver PFC. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "C-200W مشغل LED داخلي 12V/24V مصنع | CHUGAO OEM ODM",
   "desc": "الصين C-200W 200W مشغل LED داخلي, 12V/24V, PFC نشط. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "C-200W 屋内用 LED ドライバー 12V/24V 製造元 | CHUGAO OEM ODM",
   "desc": "中国 C-200W 200W 屋内用 LED ドライバー, 12V/24V, アクティブ PFC. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "C-200W 실내용 LED 구동장치 12V/24V 제조사 | CHUGAO OEM ODM",
   "desc": "중국 C-200W 200W 실내용 LED 구동장치, 12V/24V, 액티브 PFC. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "C-200W driver LED da interno 12V/24V Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina C-200W 200W driver LED da interno, 12V/24V, PFC attivo. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgc-100w": {
  "en": {
   "title": "CGC-100W Indoor LED Driver 12V/24V Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGC-100W 100W indoor LED driver, 12V/24V, active PFC. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGC-100W 室内 LED 驱动电源 12V/24V 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGC-100W 100W 室内 LED 驱动电源, 12V/24V, 主动 PFC. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGC-100W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China CGC-100W 100W driver LED de interior, 12V/24V, PFC activo. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGC-100W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China CGC-100W 100W driver LED de interior, 12V/24V, PFC ativo. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGC-100W драйвер LED для помещений 12V/24V Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGC-100W 100W драйвер LED для помещений, 12V/24V, активный PFC. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGC-100W driver LED d’intérieur 12V/24V Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGC-100W 100W driver LED d’intérieur, 12V/24V, PFC actif. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGC-100W LED-Treiber Innen 12V/24V Hersteller | CHUGAO OEM ODM",
   "desc": "China CGC-100W 100W LED-Treiber Innen, 12V/24V, aktiver PFC. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGC-100W مشغل LED داخلي 12V/24V مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGC-100W 100W مشغل LED داخلي, 12V/24V, PFC نشط. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGC-100W 屋内用 LED ドライバー 12V/24V 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGC-100W 100W 屋内用 LED ドライバー, 12V/24V, アクティブ PFC. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGC-100W 실내용 LED 구동장치 12V/24V 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGC-100W 100W 실내용 LED 구동장치, 12V/24V, 액티브 PFC. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGC-100W driver LED da interno 12V/24V Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGC-100W 100W driver LED da interno, 12V/24V, PFC attivo. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgc-200w": {
  "en": {
   "title": "CGC-200W Indoor LED Driver 12V/24V Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGC-200W 200W indoor LED driver, 12V/24V, active PFC. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGC-200W 室内 LED 驱动电源 12V/24V 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGC-200W 200W 室内 LED 驱动电源, 12V/24V, 主动 PFC. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGC-200W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China CGC-200W 200W driver LED de interior, 12V/24V, PFC activo. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGC-200W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China CGC-200W 200W driver LED de interior, 12V/24V, PFC ativo. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGC-200W драйвер LED для помещений 12V/24V Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGC-200W 200W драйвер LED для помещений, 12V/24V, активный PFC. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGC-200W driver LED d’intérieur 12V/24V Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGC-200W 200W driver LED d’intérieur, 12V/24V, PFC actif. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGC-200W LED-Treiber Innen 12V/24V Hersteller | CHUGAO OEM ODM",
   "desc": "China CGC-200W 200W LED-Treiber Innen, 12V/24V, aktiver PFC. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGC-200W مشغل LED داخلي 12V/24V مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGC-200W 200W مشغل LED داخلي, 12V/24V, PFC نشط. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGC-200W 屋内用 LED ドライバー 12V/24V 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGC-200W 200W 屋内用 LED ドライバー, 12V/24V, アクティブ PFC. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGC-200W 실내용 LED 구동장치 12V/24V 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGC-200W 200W 실내용 LED 구동장치, 12V/24V, 액티브 PFC. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGC-200W driver LED da interno 12V/24V Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGC-200W 200W driver LED da interno, 12V/24V, PFC attivo. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgc-400w": {
  "en": {
   "title": "CGC-400W Indoor LED Driver 12V/24V Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGC-400W 400W indoor LED driver, 12V/24V, active PFC. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGC-400W 室内 LED 驱动电源 12V/24V 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGC-400W 400W 室内 LED 驱动电源, 12V/24V, 主动 PFC. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGC-400W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China CGC-400W 400W driver LED de interior, 12V/24V, PFC activo. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGC-400W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China CGC-400W 400W driver LED de interior, 12V/24V, PFC ativo. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGC-400W драйвер LED для помещений 12V/24V Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGC-400W 400W драйвер LED для помещений, 12V/24V, активный PFC. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGC-400W driver LED d’intérieur 12V/24V Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGC-400W 400W driver LED d’intérieur, 12V/24V, PFC actif. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGC-400W LED-Treiber Innen 12V/24V Hersteller | CHUGAO OEM ODM",
   "desc": "China CGC-400W 400W LED-Treiber Innen, 12V/24V, aktiver PFC. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGC-400W مشغل LED داخلي 12V/24V مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGC-400W 400W مشغل LED داخلي, 12V/24V, PFC نشط. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGC-400W 屋内用 LED ドライバー 12V/24V 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGC-400W 400W 屋内用 LED ドライバー, 12V/24V, アクティブ PFC. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGC-400W 실내용 LED 구동장치 12V/24V 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGC-400W 400W 실내용 LED 구동장치, 12V/24V, 액티브 PFC. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGC-400W driver LED da interno 12V/24V Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGC-400W 400W driver LED da interno, 12V/24V, PFC attivo. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/c-60w": {
  "en": {
   "title": "C-60W Indoor LED Driver 12V/24V Manufacturer | CHUGAO OEM ODM",
   "desc": "China C-60W 60W indoor LED driver, 12V/24V, active PFC. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "C-60W 室内 LED 驱动电源 12V/24V 厂家 | CHUGAO OEM ODM",
   "desc": "中国 C-60W 60W 室内 LED 驱动电源, 12V/24V, 主动 PFC. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "C-60W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China C-60W 60W driver LED de interior, 12V/24V, PFC activo. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "C-60W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China C-60W 60W driver LED de interior, 12V/24V, PFC ativo. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "C-60W драйвер LED для помещений 12V/24V Производитель | CHUGAO OEM ODM",
   "desc": "Китай C-60W 60W драйвер LED для помещений, 12V/24V, активный PFC. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "C-60W driver LED d’intérieur 12V/24V Fabricant | CHUGAO OEM ODM",
   "desc": "Chine C-60W 60W driver LED d’intérieur, 12V/24V, PFC actif. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "C-60W LED-Treiber Innen 12V/24V Hersteller | CHUGAO OEM ODM",
   "desc": "China C-60W 60W LED-Treiber Innen, 12V/24V, aktiver PFC. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "C-60W مشغل LED داخلي 12V/24V مصنع | CHUGAO OEM ODM",
   "desc": "الصين C-60W 60W مشغل LED داخلي, 12V/24V, PFC نشط. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "C-60W 屋内用 LED ドライバー 12V/24V 製造元 | CHUGAO OEM ODM",
   "desc": "中国 C-60W 60W 屋内用 LED ドライバー, 12V/24V, アクティブ PFC. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "C-60W 실내용 LED 구동장치 12V/24V 제조사 | CHUGAO OEM ODM",
   "desc": "중국 C-60W 60W 실내용 LED 구동장치, 12V/24V, 액티브 PFC. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "C-60W driver LED da interno 12V/24V Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina C-60W 60W driver LED da interno, 12V/24V, PFC attivo. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgc-48w": {
  "en": {
   "title": "CGC-48W Indoor LED Driver 12V/24V Manufacturer | CHUGAO OEM ODM",
   "desc": "China CGC-48W 48W indoor LED driver, 12V/24V, active PFC. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGC-48W 室内 LED 驱动电源 12V/24V 厂家 | CHUGAO OEM ODM",
   "desc": "中国 CGC-48W 48W 室内 LED 驱动电源, 12V/24V, 主动 PFC. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGC-48W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China CGC-48W 48W driver LED de interior, 12V/24V, PFC activo. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGC-48W driver LED de interior 12V/24V Fabricante | CHUGAO OEM ODM",
   "desc": "China CGC-48W 48W driver LED de interior, 12V/24V, PFC ativo. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGC-48W драйвер LED для помещений 12V/24V Производитель | CHUGAO OEM ODM",
   "desc": "Китай CGC-48W 48W драйвер LED для помещений, 12V/24V, активный PFC. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGC-48W driver LED d’intérieur 12V/24V Fabricant | CHUGAO OEM ODM",
   "desc": "Chine CGC-48W 48W driver LED d’intérieur, 12V/24V, PFC actif. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGC-48W LED-Treiber Innen 12V/24V Hersteller | CHUGAO OEM ODM",
   "desc": "China CGC-48W 48W LED-Treiber Innen, 12V/24V, aktiver PFC. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGC-48W مشغل LED داخلي 12V/24V مصنع | CHUGAO OEM ODM",
   "desc": "الصين CGC-48W 48W مشغل LED داخلي, 12V/24V, PFC نشط. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGC-48W 屋内用 LED ドライバー 12V/24V 製造元 | CHUGAO OEM ODM",
   "desc": "中国 CGC-48W 48W 屋内用 LED ドライバー, 12V/24V, アクティブ PFC. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGC-48W 실내용 LED 구동장치 12V/24V 제조사 | CHUGAO OEM ODM",
   "desc": "중국 CGC-48W 48W 실내용 LED 구동장치, 12V/24V, 액티브 PFC. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGC-48W driver LED da interno 12V/24V Fabbrica | CHUGAO OEM ODM",
   "desc": "Cina CGC-48W 48W driver LED da interno, 12V/24V, PFC attivo. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgb-100w": {
  "en": {
   "title": "CGB-100W dimmable Indoor LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-100W 100W dimmable indoor LED driver, 12V/24V, 0-10V/PWM. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGB-100W 可调光 室内 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGB-100W 100W 可调光 室内 LED 驱动电源, 12V/24V, 0-10V/PWM. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGB-100W regulable driver LED de interior 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-100W 100W regulable driver LED de interior, 12V/24V, 0-10V/PWM. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGB-100W dimerizável driver LED de interior 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-100W 100W dimerizável driver LED de interior, 12V/24V, 0-10V/PWM. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGB-100W диммируемый драйвер LED для помещений 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGB-100W 100W диммируемый драйвер LED для помещений, 12V/24V, 0-10V/PWM. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGB-100W dimmable driver LED d’intérieur 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGB-100W 100W dimmable driver LED d’intérieur, 12V/24V, 0-10V/PWM. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGB-100W dimmbarer LED-Treiber Innen 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-100W 100W dimmbarer LED-Treiber Innen, 12V/24V, 0-10V/PWM. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGB-100W قابل للتعتيم مشغل LED داخلي 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGB-100W 100W قابل للتعتيم مشغل LED داخلي, 12V/24V, 0-10V/PWM. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGB-100W 調光対応 屋内用 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGB-100W 100W 調光対応 屋内用 LED ドライバー, 12V/24V, 0-10V/PWM. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGB-100W 디밍 실내용 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGB-100W 100W 디밍 실내용 LED 구동장치, 12V/24V, 0-10V/PWM. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGB-100W dimerizzabile driver LED da interno 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGB-100W 100W dimerizzabile driver LED da interno, 12V/24V, 0-10V/PWM. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgb-200w": {
  "en": {
   "title": "CGB-200W dimmable Indoor LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-200W 200W dimmable indoor LED driver, 12V/24V, 0-10V/PWM. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGB-200W 可调光 室内 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGB-200W 200W 可调光 室内 LED 驱动电源, 12V/24V, 0-10V/PWM. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGB-200W regulable driver LED de interior 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-200W 200W regulable driver LED de interior, 12V/24V, 0-10V/PWM. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGB-200W dimerizável driver LED de interior 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-200W 200W dimerizável driver LED de interior, 12V/24V, 0-10V/PWM. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGB-200W диммируемый драйвер LED для помещений 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGB-200W 200W диммируемый драйвер LED для помещений, 12V/24V, 0-10V/PWM. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGB-200W dimmable driver LED d’intérieur 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGB-200W 200W dimmable driver LED d’intérieur, 12V/24V, 0-10V/PWM. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGB-200W dimmbarer LED-Treiber Innen 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-200W 200W dimmbarer LED-Treiber Innen, 12V/24V, 0-10V/PWM. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGB-200W قابل للتعتيم مشغل LED داخلي 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGB-200W 200W قابل للتعتيم مشغل LED داخلي, 12V/24V, 0-10V/PWM. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGB-200W 調光対応 屋内用 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGB-200W 200W 調光対応 屋内用 LED ドライバー, 12V/24V, 0-10V/PWM. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGB-200W 디밍 실내용 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGB-200W 200W 디밍 실내용 LED 구동장치, 12V/24V, 0-10V/PWM. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGB-200W dimerizzabile driver LED da interno 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGB-200W 200W dimerizzabile driver LED da interno, 12V/24V, 0-10V/PWM. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgb-400w": {
  "en": {
   "title": "CGB-400W dimmable Indoor LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-400W 400W dimmable indoor LED driver, 12V/24V, 0-10V/PWM. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "CGB-400W 可调光 室内 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGB-400W 400W 可调光 室内 LED 驱动电源, 12V/24V, 0-10V/PWM. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "CGB-400W regulable driver LED de interior 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-400W 400W regulable driver LED de interior, 12V/24V, 0-10V/PWM. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "CGB-400W dimerizável driver LED de interior 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-400W 400W dimerizável driver LED de interior, 12V/24V, 0-10V/PWM. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "CGB-400W диммируемый драйвер LED для помещений 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGB-400W 400W диммируемый драйвер LED для помещений, 12V/24V, 0-10V/PWM. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "CGB-400W dimmable driver LED d’intérieur 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGB-400W 400W dimmable driver LED d’intérieur, 12V/24V, 0-10V/PWM. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "CGB-400W dimmbarer LED-Treiber Innen 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGB-400W 400W dimmbarer LED-Treiber Innen, 12V/24V, 0-10V/PWM. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "CGB-400W قابل للتعتيم مشغل LED داخلي 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGB-400W 400W قابل للتعتيم مشغل LED داخلي, 12V/24V, 0-10V/PWM. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "CGB-400W 調光対応 屋内用 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGB-400W 400W 調光対応 屋内用 LED ドライバー, 12V/24V, 0-10V/PWM. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "CGB-400W 디밍 실내용 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGB-400W 400W 디밍 실내용 LED 구동장치, 12V/24V, 0-10V/PWM. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "CGB-400W dimerizzabile driver LED da interno 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGB-400W 400W dimerizzabile driver LED da interno, 12V/24V, 0-10V/PWM. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/cgf-24w": {
  "en": {
   "title": "CGF-24W IP67 Waterproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-24W 24W IP67 waterproof LED driver, 12V/24V. fully potted, salt-spray tested, CE/RoHS, 3-year warranty."
  },
  "zh": {
   "title": "CGF-24W IP67 防水 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-24W 24W IP67 防水 LED 驱动电源, 12V/24V. 全灌封、盐雾测试, CE/RoHS, 3 年质保."
  },
  "es": {
   "title": "CGF-24W driver LED IP67 impermeable 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-24W 24W driver LED IP67 impermeable, 12V/24V. encapsulado total, probado en niebla salina, CE/RoHS, garantía 3 años."
  },
  "pt": {
   "title": "CGF-24W driver LED IP67 à prova d’água 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-24W 24W driver LED IP67 à prova d’água, 12V/24V. encapsulamento total, teste de névoa salina, CE/RoHS, garantia 3 anos."
  },
  "ru": {
   "title": "CGF-24W водонепроницаемый драйвер LED IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGF-24W 24W водонепроницаемый драйвер LED IP67, 12V/24V. полная заливка, тест соляным туманом, CE/RoHS, гарантия 3 года."
  },
  "fr": {
   "title": "CGF-24W driver LED IP67 étanche 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGF-24W 24W driver LED IP67 étanche, 12V/24V. entièrement enrobés, testés au brouillard salin, CE/RoHS, garantie 3 ans."
  },
  "de": {
   "title": "CGF-24W IP67 wasserdichter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-24W 24W IP67 wasserdichter LED-Treiber, 12V/24V. komplett vergossen, salzsprühgeprüft, CE/RoHS, 3 Jahre Garantie."
  },
  "ar": {
   "title": "CGF-24W مشغل LED مقاوم للماء IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGF-24W 24W مشغل LED مقاوم للماء IP67, 12V/24V. معبأة بالكامل، ومختبرة برذاذ الملح, CE/RoHS, ضمان 3 سنوات."
  },
  "ja": {
   "title": "CGF-24W IP67 防水 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-24W 24W IP67 防水 LED ドライバー, 12V/24V. 完全ポッティング、塩水噴霧試験済み, CE/RoHS, 3 年保証."
  },
  "ko": {
   "title": "CGF-24W IP67 방수 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGF-24W 24W IP67 방수 LED 구동장치, 12V/24V. 완전 포팅, 염수 분무 시험, CE/RoHS, 3년 보증."
  },
  "it": {
   "title": "CGF-24W driver LED impermeabile IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGF-24W 24W driver LED impermeabile IP67, 12V/24V. completamente sigillati, test nebbia salina, CE/RoHS, garanzia 3 anni."
  }
 },
 "products/cgf-100w": {
  "en": {
   "title": "CGF-100W IP67 Waterproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-100W 100W IP67 waterproof LED driver, 12V/24V. fully potted, salt-spray tested, CE/RoHS, 3-year warranty."
  },
  "zh": {
   "title": "CGF-100W IP67 防水 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-100W 100W IP67 防水 LED 驱动电源, 12V/24V. 全灌封、盐雾测试, CE/RoHS, 3 年质保."
  },
  "es": {
   "title": "CGF-100W driver LED IP67 impermeable 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-100W 100W driver LED IP67 impermeable, 12V/24V. encapsulado total, probado en niebla salina, CE/RoHS, garantía 3 años."
  },
  "pt": {
   "title": "CGF-100W driver LED IP67 à prova d’água 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-100W 100W driver LED IP67 à prova d’água, 12V/24V. encapsulamento total, teste de névoa salina, CE/RoHS, garantia 3 anos."
  },
  "ru": {
   "title": "CGF-100W водонепроницаемый драйвер LED IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGF-100W 100W водонепроницаемый драйвер LED IP67, 12V/24V. полная заливка, тест соляным туманом, CE/RoHS, гарантия 3 года."
  },
  "fr": {
   "title": "CGF-100W driver LED IP67 étanche 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGF-100W 100W driver LED IP67 étanche, 12V/24V. entièrement enrobés, testés au brouillard salin, CE/RoHS, garantie 3 ans."
  },
  "de": {
   "title": "CGF-100W IP67 wasserdichter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-100W 100W IP67 wasserdichter LED-Treiber, 12V/24V. komplett vergossen, salzsprühgeprüft, CE/RoHS, 3 Jahre Garantie."
  },
  "ar": {
   "title": "CGF-100W مشغل LED مقاوم للماء IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGF-100W 100W مشغل LED مقاوم للماء IP67, 12V/24V. معبأة بالكامل، ومختبرة برذاذ الملح, CE/RoHS, ضمان 3 سنوات."
  },
  "ja": {
   "title": "CGF-100W IP67 防水 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-100W 100W IP67 防水 LED ドライバー, 12V/24V. 完全ポッティング、塩水噴霧試験済み, CE/RoHS, 3 年保証."
  },
  "ko": {
   "title": "CGF-100W IP67 방수 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGF-100W 100W IP67 방수 LED 구동장치, 12V/24V. 완전 포팅, 염수 분무 시험, CE/RoHS, 3년 보증."
  },
  "it": {
   "title": "CGF-100W driver LED impermeabile IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGF-100W 100W driver LED impermeabile IP67, 12V/24V. completamente sigillati, test nebbia salina, CE/RoHS, garanzia 3 anni."
  }
 },
 "products/cgf-200w": {
  "en": {
   "title": "CGF-200W IP67 Waterproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-200W 200W IP67 waterproof LED driver, 12V/24V. fully potted, salt-spray tested, CE/RoHS, 3-year warranty."
  },
  "zh": {
   "title": "CGF-200W IP67 防水 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-200W 200W IP67 防水 LED 驱动电源, 12V/24V. 全灌封、盐雾测试, CE/RoHS, 3 年质保."
  },
  "es": {
   "title": "CGF-200W driver LED IP67 impermeable 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-200W 200W driver LED IP67 impermeable, 12V/24V. encapsulado total, probado en niebla salina, CE/RoHS, garantía 3 años."
  },
  "pt": {
   "title": "CGF-200W driver LED IP67 à prova d’água 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-200W 200W driver LED IP67 à prova d’água, 12V/24V. encapsulamento total, teste de névoa salina, CE/RoHS, garantia 3 anos."
  },
  "ru": {
   "title": "CGF-200W водонепроницаемый драйвер LED IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGF-200W 200W водонепроницаемый драйвер LED IP67, 12V/24V. полная заливка, тест соляным туманом, CE/RoHS, гарантия 3 года."
  },
  "fr": {
   "title": "CGF-200W driver LED IP67 étanche 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGF-200W 200W driver LED IP67 étanche, 12V/24V. entièrement enrobés, testés au brouillard salin, CE/RoHS, garantie 3 ans."
  },
  "de": {
   "title": "CGF-200W IP67 wasserdichter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-200W 200W IP67 wasserdichter LED-Treiber, 12V/24V. komplett vergossen, salzsprühgeprüft, CE/RoHS, 3 Jahre Garantie."
  },
  "ar": {
   "title": "CGF-200W مشغل LED مقاوم للماء IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGF-200W 200W مشغل LED مقاوم للماء IP67, 12V/24V. معبأة بالكامل، ومختبرة برذاذ الملح, CE/RoHS, ضمان 3 سنوات."
  },
  "ja": {
   "title": "CGF-200W IP67 防水 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-200W 200W IP67 防水 LED ドライバー, 12V/24V. 完全ポッティング、塩水噴霧試験済み, CE/RoHS, 3 年保証."
  },
  "ko": {
   "title": "CGF-200W IP67 방수 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGF-200W 200W IP67 방수 LED 구동장치, 12V/24V. 완전 포팅, 염수 분무 시험, CE/RoHS, 3년 보증."
  },
  "it": {
   "title": "CGF-200W driver LED impermeabile IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGF-200W 200W driver LED impermeabile IP67, 12V/24V. completamente sigillati, test nebbia salina, CE/RoHS, garanzia 3 anni."
  }
 },
 "products/cgf-400w": {
  "en": {
   "title": "CGF-400W IP67 Waterproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-400W 400W IP67 waterproof LED driver, 12V/24V. fully potted, salt-spray tested, CE/RoHS, 3-year warranty."
  },
  "zh": {
   "title": "CGF-400W IP67 防水 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-400W 400W IP67 防水 LED 驱动电源, 12V/24V. 全灌封、盐雾测试, CE/RoHS, 3 年质保."
  },
  "es": {
   "title": "CGF-400W driver LED IP67 impermeable 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-400W 400W driver LED IP67 impermeable, 12V/24V. encapsulado total, probado en niebla salina, CE/RoHS, garantía 3 años."
  },
  "pt": {
   "title": "CGF-400W driver LED IP67 à prova d’água 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-400W 400W driver LED IP67 à prova d’água, 12V/24V. encapsulamento total, teste de névoa salina, CE/RoHS, garantia 3 anos."
  },
  "ru": {
   "title": "CGF-400W водонепроницаемый драйвер LED IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGF-400W 400W водонепроницаемый драйвер LED IP67, 12V/24V. полная заливка, тест соляным туманом, CE/RoHS, гарантия 3 года."
  },
  "fr": {
   "title": "CGF-400W driver LED IP67 étanche 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGF-400W 400W driver LED IP67 étanche, 12V/24V. entièrement enrobés, testés au brouillard salin, CE/RoHS, garantie 3 ans."
  },
  "de": {
   "title": "CGF-400W IP67 wasserdichter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-400W 400W IP67 wasserdichter LED-Treiber, 12V/24V. komplett vergossen, salzsprühgeprüft, CE/RoHS, 3 Jahre Garantie."
  },
  "ar": {
   "title": "CGF-400W مشغل LED مقاوم للماء IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGF-400W 400W مشغل LED مقاوم للماء IP67, 12V/24V. معبأة بالكامل، ومختبرة برذاذ الملح, CE/RoHS, ضمان 3 سنوات."
  },
  "ja": {
   "title": "CGF-400W IP67 防水 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-400W 400W IP67 防水 LED ドライバー, 12V/24V. 完全ポッティング、塩水噴霧試験済み, CE/RoHS, 3 年保証."
  },
  "ko": {
   "title": "CGF-400W IP67 방수 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGF-400W 400W IP67 방수 LED 구동장치, 12V/24V. 완전 포팅, 염수 분무 시험, CE/RoHS, 3년 보증."
  },
  "it": {
   "title": "CGF-400W driver LED impermeabile IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGF-400W 400W driver LED impermeabile IP67, 12V/24V. completamente sigillati, test nebbia salina, CE/RoHS, garanzia 3 anni."
  }
 },
 "products/cgf-36w": {
  "en": {
   "title": "CGF-36W IP67 Waterproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-36W 36W IP67 waterproof LED driver, 12V/24V. fully potted, salt-spray tested, CE/RoHS, 3-year warranty."
  },
  "zh": {
   "title": "CGF-36W IP67 防水 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-36W 36W IP67 防水 LED 驱动电源, 12V/24V. 全灌封、盐雾测试, CE/RoHS, 3 年质保."
  },
  "es": {
   "title": "CGF-36W driver LED IP67 impermeable 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-36W 36W driver LED IP67 impermeable, 12V/24V. encapsulado total, probado en niebla salina, CE/RoHS, garantía 3 años."
  },
  "pt": {
   "title": "CGF-36W driver LED IP67 à prova d’água 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-36W 36W driver LED IP67 à prova d’água, 12V/24V. encapsulamento total, teste de névoa salina, CE/RoHS, garantia 3 anos."
  },
  "ru": {
   "title": "CGF-36W водонепроницаемый драйвер LED IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGF-36W 36W водонепроницаемый драйвер LED IP67, 12V/24V. полная заливка, тест соляным туманом, CE/RoHS, гарантия 3 года."
  },
  "fr": {
   "title": "CGF-36W driver LED IP67 étanche 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGF-36W 36W driver LED IP67 étanche, 12V/24V. entièrement enrobés, testés au brouillard salin, CE/RoHS, garantie 3 ans."
  },
  "de": {
   "title": "CGF-36W IP67 wasserdichter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-36W 36W IP67 wasserdichter LED-Treiber, 12V/24V. komplett vergossen, salzsprühgeprüft, CE/RoHS, 3 Jahre Garantie."
  },
  "ar": {
   "title": "CGF-36W مشغل LED مقاوم للماء IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGF-36W 36W مشغل LED مقاوم للماء IP67, 12V/24V. معبأة بالكامل، ومختبرة برذاذ الملح, CE/RoHS, ضمان 3 سنوات."
  },
  "ja": {
   "title": "CGF-36W IP67 防水 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-36W 36W IP67 防水 LED ドライバー, 12V/24V. 完全ポッティング、塩水噴霧試験済み, CE/RoHS, 3 年保証."
  },
  "ko": {
   "title": "CGF-36W IP67 방수 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGF-36W 36W IP67 방수 LED 구동장치, 12V/24V. 완전 포팅, 염수 분무 시험, CE/RoHS, 3년 보증."
  },
  "it": {
   "title": "CGF-36W driver LED impermeabile IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGF-36W 36W driver LED impermeabile IP67, 12V/24V. completamente sigillati, test nebbia salina, CE/RoHS, garanzia 3 anni."
  }
 },
 "products/cgf-60w": {
  "en": {
   "title": "CGF-60W IP67 Waterproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-60W 60W IP67 waterproof LED driver, 12V/24V. fully potted, salt-spray tested, CE/RoHS, 3-year warranty."
  },
  "zh": {
   "title": "CGF-60W IP67 防水 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-60W 60W IP67 防水 LED 驱动电源, 12V/24V. 全灌封、盐雾测试, CE/RoHS, 3 年质保."
  },
  "es": {
   "title": "CGF-60W driver LED IP67 impermeable 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-60W 60W driver LED IP67 impermeable, 12V/24V. encapsulado total, probado en niebla salina, CE/RoHS, garantía 3 años."
  },
  "pt": {
   "title": "CGF-60W driver LED IP67 à prova d’água 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-60W 60W driver LED IP67 à prova d’água, 12V/24V. encapsulamento total, teste de névoa salina, CE/RoHS, garantia 3 anos."
  },
  "ru": {
   "title": "CGF-60W водонепроницаемый драйвер LED IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGF-60W 60W водонепроницаемый драйвер LED IP67, 12V/24V. полная заливка, тест соляным туманом, CE/RoHS, гарантия 3 года."
  },
  "fr": {
   "title": "CGF-60W driver LED IP67 étanche 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGF-60W 60W driver LED IP67 étanche, 12V/24V. entièrement enrobés, testés au brouillard salin, CE/RoHS, garantie 3 ans."
  },
  "de": {
   "title": "CGF-60W IP67 wasserdichter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-60W 60W IP67 wasserdichter LED-Treiber, 12V/24V. komplett vergossen, salzsprühgeprüft, CE/RoHS, 3 Jahre Garantie."
  },
  "ar": {
   "title": "CGF-60W مشغل LED مقاوم للماء IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGF-60W 60W مشغل LED مقاوم للماء IP67, 12V/24V. معبأة بالكامل، ومختبرة برذاذ الملح, CE/RoHS, ضمان 3 سنوات."
  },
  "ja": {
   "title": "CGF-60W IP67 防水 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-60W 60W IP67 防水 LED ドライバー, 12V/24V. 完全ポッティング、塩水噴霧試験済み, CE/RoHS, 3 年保証."
  },
  "ko": {
   "title": "CGF-60W IP67 방수 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGF-60W 60W IP67 방수 LED 구동장치, 12V/24V. 완전 포팅, 염수 분무 시험, CE/RoHS, 3년 보증."
  },
  "it": {
   "title": "CGF-60W driver LED impermeabile IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGF-60W 60W driver LED impermeabile IP67, 12V/24V. completamente sigillati, test nebbia salina, CE/RoHS, garanzia 3 anni."
  }
 },
 "products/cgf-150w": {
  "en": {
   "title": "CGF-150W IP67 Waterproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-150W 150W IP67 waterproof LED driver, 12V/24V. fully potted, salt-spray tested, CE/RoHS, 3-year warranty."
  },
  "zh": {
   "title": "CGF-150W IP67 防水 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-150W 150W IP67 防水 LED 驱动电源, 12V/24V. 全灌封、盐雾测试, CE/RoHS, 3 年质保."
  },
  "es": {
   "title": "CGF-150W driver LED IP67 impermeable 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-150W 150W driver LED IP67 impermeable, 12V/24V. encapsulado total, probado en niebla salina, CE/RoHS, garantía 3 años."
  },
  "pt": {
   "title": "CGF-150W driver LED IP67 à prova d’água 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-150W 150W driver LED IP67 à prova d’água, 12V/24V. encapsulamento total, teste de névoa salina, CE/RoHS, garantia 3 anos."
  },
  "ru": {
   "title": "CGF-150W водонепроницаемый драйвер LED IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGF-150W 150W водонепроницаемый драйвер LED IP67, 12V/24V. полная заливка, тест соляным туманом, CE/RoHS, гарантия 3 года."
  },
  "fr": {
   "title": "CGF-150W driver LED IP67 étanche 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGF-150W 150W driver LED IP67 étanche, 12V/24V. entièrement enrobés, testés au brouillard salin, CE/RoHS, garantie 3 ans."
  },
  "de": {
   "title": "CGF-150W IP67 wasserdichter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-150W 150W IP67 wasserdichter LED-Treiber, 12V/24V. komplett vergossen, salzsprühgeprüft, CE/RoHS, 3 Jahre Garantie."
  },
  "ar": {
   "title": "CGF-150W مشغل LED مقاوم للماء IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGF-150W 150W مشغل LED مقاوم للماء IP67, 12V/24V. معبأة بالكامل، ومختبرة برذاذ الملح, CE/RoHS, ضمان 3 سنوات."
  },
  "ja": {
   "title": "CGF-150W IP67 防水 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-150W 150W IP67 防水 LED ドライバー, 12V/24V. 完全ポッティング、塩水噴霧試験済み, CE/RoHS, 3 年保証."
  },
  "ko": {
   "title": "CGF-150W IP67 방수 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGF-150W 150W IP67 방수 LED 구동장치, 12V/24V. 완전 포팅, 염수 분무 시험, CE/RoHS, 3년 보증."
  },
  "it": {
   "title": "CGF-150W driver LED impermeabile IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGF-150W 150W driver LED impermeabile IP67, 12V/24V. completamente sigillati, test nebbia salina, CE/RoHS, garanzia 3 anni."
  }
 },
 "products/cgf-300w": {
  "en": {
   "title": "CGF-300W IP67 Waterproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-300W 300W IP67 waterproof LED driver, 12V/24V. fully potted, salt-spray tested, CE/RoHS, 3-year warranty."
  },
  "zh": {
   "title": "CGF-300W IP67 防水 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-300W 300W IP67 防水 LED 驱动电源, 12V/24V. 全灌封、盐雾测试, CE/RoHS, 3 年质保."
  },
  "es": {
   "title": "CGF-300W driver LED IP67 impermeable 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-300W 300W driver LED IP67 impermeable, 12V/24V. encapsulado total, probado en niebla salina, CE/RoHS, garantía 3 años."
  },
  "pt": {
   "title": "CGF-300W driver LED IP67 à prova d’água 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-300W 300W driver LED IP67 à prova d’água, 12V/24V. encapsulamento total, teste de névoa salina, CE/RoHS, garantia 3 anos."
  },
  "ru": {
   "title": "CGF-300W водонепроницаемый драйвер LED IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай CGF-300W 300W водонепроницаемый драйвер LED IP67, 12V/24V. полная заливка, тест соляным туманом, CE/RoHS, гарантия 3 года."
  },
  "fr": {
   "title": "CGF-300W driver LED IP67 étanche 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine CGF-300W 300W driver LED IP67 étanche, 12V/24V. entièrement enrobés, testés au brouillard salin, CE/RoHS, garantie 3 ans."
  },
  "de": {
   "title": "CGF-300W IP67 wasserdichter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China CGF-300W 300W IP67 wasserdichter LED-Treiber, 12V/24V. komplett vergossen, salzsprühgeprüft, CE/RoHS, 3 Jahre Garantie."
  },
  "ar": {
   "title": "CGF-300W مشغل LED مقاوم للماء IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين CGF-300W 300W مشغل LED مقاوم للماء IP67, 12V/24V. معبأة بالكامل، ومختبرة برذاذ الملح, CE/RoHS, ضمان 3 سنوات."
  },
  "ja": {
   "title": "CGF-300W IP67 防水 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 CGF-300W 300W IP67 防水 LED ドライバー, 12V/24V. 完全ポッティング、塩水噴霧試験済み, CE/RoHS, 3 年保証."
  },
  "ko": {
   "title": "CGF-300W IP67 방수 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 CGF-300W 300W IP67 방수 LED 구동장치, 12V/24V. 완전 포팅, 염수 분무 시험, CE/RoHS, 3년 보증."
  },
  "it": {
   "title": "CGF-300W driver LED impermeabile IP67 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina CGF-300W 300W driver LED impermeabile IP67, 12V/24V. completamente sigillati, test nebbia salina, CE/RoHS, garanzia 3 anni."
  }
 },
 "products/fyg-400w": {
  "en": {
   "title": "FYG-400W IP65 Rainproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China FYG-400W 400W IP65 rainproof LED driver, 12V/24V, metal case. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "FYG-400W IP65 防雨 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 FYG-400W 400W IP65 防雨 LED 驱动电源, 12V/24V, 金属外壳. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "FYG-400W driver LED IP65 anti-lluvia 12V/24V | CHUGAO OEM ODM",
   "desc": "China FYG-400W 400W driver LED IP65 anti-lluvia, 12V/24V, carcasa metálica. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "FYG-400W driver LED IP65 à prova de chuva 12V/24V | CHUGAO OEM ODM",
   "desc": "China FYG-400W 400W driver LED IP65 à prova de chuva, 12V/24V, caixa metálica. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "FYG-400W дождезащищённый драйвер LED IP65 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай FYG-400W 400W дождезащищённый драйвер LED IP65, 12V/24V, металлокорпус. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "FYG-400W driver LED IP65 anti-pluie 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine FYG-400W 400W driver LED IP65 anti-pluie, 12V/24V, boîtier métallique. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "FYG-400W IP65 regengeschützter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China FYG-400W 400W IP65 regengeschützter LED-Treiber, 12V/24V, Metallgehäuse. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "FYG-400W مشغل LED مقاوم للمطر IP65 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين FYG-400W 400W مشغل LED مقاوم للمطر IP65, 12V/24V, هيكل معدني. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "FYG-400W IP65 防雨 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 FYG-400W 400W IP65 防雨 LED ドライバー, 12V/24V, 金属ケース. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "FYG-400W IP65 방우 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 FYG-400W 400W IP65 방우 LED 구동장치, 12V/24V, 금속 케이스. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "FYG-400W driver LED anti-pioggia IP65 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina FYG-400W 400W driver LED anti-pioggia IP65, 12V/24V, custodia metallica. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 },
 "products/fyg-600w": {
  "en": {
   "title": "FYG-600W IP65 Rainproof LED Driver 12V/24V | CHUGAO OEM ODM",
   "desc": "China FYG-600W 600W IP65 rainproof LED driver, 12V/24V, metal case. CE/RoHS, 3-year warranty, 50 pcs MOQ, OEM ODM."
  },
  "zh": {
   "title": "FYG-600W IP65 防雨 LED 驱动电源 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 FYG-600W 600W IP65 防雨 LED 驱动电源, 12V/24V, 金属外壳. CE/RoHS, 3 年质保, 50 台起订, OEM ODM."
  },
  "es": {
   "title": "FYG-600W driver LED IP65 anti-lluvia 12V/24V | CHUGAO OEM ODM",
   "desc": "China FYG-600W 600W driver LED IP65 anti-lluvia, 12V/24V, carcasa metálica. CE/RoHS, garantía 3 años, pedido mínimo 50 uds, OEM ODM."
  },
  "pt": {
   "title": "FYG-600W driver LED IP65 à prova de chuva 12V/24V | CHUGAO OEM ODM",
   "desc": "China FYG-600W 600W driver LED IP65 à prova de chuva, 12V/24V, caixa metálica. CE/RoHS, garantia 3 anos, pedido mínimo 50 peças, OEM ODM."
  },
  "ru": {
   "title": "FYG-600W дождезащищённый драйвер LED IP65 12V/24V | CHUGAO OEM ODM",
   "desc": "Китай FYG-600W 600W дождезащищённый драйвер LED IP65, 12V/24V, металлокорпус. CE/RoHS, гарантия 3 года, минимальный заказ 50 шт, OEM ODM."
  },
  "fr": {
   "title": "FYG-600W driver LED IP65 anti-pluie 12V/24V | CHUGAO OEM ODM",
   "desc": "Chine FYG-600W 600W driver LED IP65 anti-pluie, 12V/24V, boîtier métallique. CE/RoHS, garantie 3 ans, commande minimum 50 pièces, OEM ODM."
  },
  "de": {
   "title": "FYG-600W IP65 regengeschützter LED-Treiber 12V/24V | CHUGAO OEM ODM",
   "desc": "China FYG-600W 600W IP65 regengeschützter LED-Treiber, 12V/24V, Metallgehäuse. CE/RoHS, 3 Jahre Garantie, Mindestmenge 50 Stk, OEM ODM."
  },
  "ar": {
   "title": "FYG-600W مشغل LED مقاوم للمطر IP65 12V/24V | CHUGAO OEM ODM",
   "desc": "الصين FYG-600W 600W مشغل LED مقاوم للمطر IP65, 12V/24V, هيكل معدني. CE/RoHS, ضمان 3 سنوات, الحد الأدنى 50 قطعة, OEM ODM."
  },
  "ja": {
   "title": "FYG-600W IP65 防雨 LED ドライバー 12V/24V | CHUGAO OEM ODM",
   "desc": "中国 FYG-600W 600W IP65 防雨 LED ドライバー, 12V/24V, 金属ケース. CE/RoHS, 3 年保証, 最小ロット 50 台, OEM ODM."
  },
  "ko": {
   "title": "FYG-600W IP65 방우 LED 구동장치 12V/24V | CHUGAO OEM ODM",
   "desc": "중국 FYG-600W 600W IP65 방우 LED 구동장치, 12V/24V, 금속 케이스. CE/RoHS, 3년 보증, 최소 주문 50대, OEM ODM."
  },
  "it": {
   "title": "FYG-600W driver LED anti-pioggia IP65 12V/24V | CHUGAO OEM ODM",
   "desc": "Cina FYG-600W 600W driver LED anti-pioggia IP65, 12V/24V, custodia metallica. CE/RoHS, garanzia 3 anni, ordine minimo 50 pz, OEM ODM."
  }
 }
}
